Q1

In [1]:
def secret(a):
    c=a[2:].replace(".", " ")
    c = ''.join((a[0]," class=","'",c,"'","></",a[0],">"))
    return c

In [2]:
secret("p.one.two.three") 

"p class='one two three'></p>"

In [3]:
secret("p.one") 

"p class='one'></p>"

In [4]:
secret("p.four.five") 

"p class='four five'></p>"

Q2

In [5]:
def count_lone_ones(a):
    a=[i for i in str(a)]
    c=0
    if a[0]=='1'and a[1]!='1':c+=1
    for i in range (1,len(a)):
        if a[i-1]!='1' and a[i]=='1':c+=1
    return c

In [6]:
count_lone_ones(101) 

2

In [7]:
count_lone_ones(1111) 

0

In [8]:
count_lone_ones(1191)

1

In [9]:
count_lone_ones(10101) 

3

In [10]:
count_lone_ones(462)

0

Q3

In [11]:
import numpy as np

In [12]:
def printGrid(a, b) :
    c=[]
    for i in range(a):
        c1=[]
        for j in range(b):
            c1.append(i+1+3*j)
        c.append(c1)
    return np.array(c)  

In [13]:
printGrid(3, 6) 

array([[ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17],
       [ 3,  6,  9, 12, 15, 18]])

In [14]:
printGrid(5, 3) 

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9],
       [ 4,  7, 10],
       [ 5,  8, 11]])

In [15]:
printGrid(4, 1) 

array([[1],
       [2],
       [3],
       [4]])

Q4

In [16]:
def min_miss_pos(a):
    a.sort()
    b=[i for i in range(1,100)]
    for i in b:
        if i not in a: return i

In [17]:
min_miss_pos([-2, 6, 4, 5, 7, -1, 1, 3, 6, -2, 9, 10, 2, 2]) 

8

In [18]:
min_miss_pos([5, 9, -2, 0, 1, 3, 9, 3, 8, 9]) 

2

In [19]:
min_miss_pos([0, 4, 4, -1, 9, 4, 5, 2, 10, 7, 6, 3, 10, 9]) 

1

Q5

In [20]:
customers = {
  "Batman": [22, 30, 11, 17, 15, 52, 27, 12],
  "Spider-Man": [5, 17, 30, 33, 40, 22, 26, 10, 11, 45]
}


In [21]:
for i in customers:
    print(sorted(customers[i]))


[11, 12, 15, 17, 22, 27, 30, 52]
[5, 10, 11, 17, 22, 26, 30, 33, 40, 45]


In [22]:
def pizza_points(customers, a, b):
    c=[]
    for i in customers:
        c2=sorted(customers[i],reverse=True)
        c1=0
        for j in range (a):
            if c2[j]>=b:c1+=1
        if c1==a:c.append(i)
    return c
            

In [23]:
pizza_points(customers, 5, 20) 

['Spider-Man']

In [24]:
pizza_points(customers, 3, 10) 

['Batman', 'Spider-Man']

In [25]:
pizza_points(customers, 5, 100) 

[]